version: '1.0.{build}'

configuration:
    - Debug
    - Release

os: Visual Studio 2017

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017" ..

build_script:
    - cmake --build . --config %CONFIGURATION%
    - ctest -C %CONFIGURATION%
